objects/Contact.object
<CustomObject><fields>
        <fullName>Biological_Sex__c</fullName>
        <description>User registration data passed by Helix Marketplace API.</description>
        <inlineHelpText>User registration data passed by Helix Marketplace API.</inlineHelpText>
        <label>Biological Sex</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Naturally_Black_Hair__c</fullName>
        <description>User registration data passed by Helix Marketplace API.</description>
        <inlineHelpText>User registration data passed by Helix Marketplace API.</inlineHelpText>
        <label>Naturally Black Hair?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>I don't know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>userid__c</fullName>
        <description>User registration data passed by Helix Marketplace API.</description>
        <externalId>true</externalId>
        <inlineHelpText>User registration data passed by Helix Marketplace API.</inlineHelpText>
        <label>UserID</label>
        <length>39</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/OrderItem.object
<CustomObject><fields>
        <fullName>Analysis_Workflow__c</fullName>
        <description>Set on OP creation. Applies to kit products only. Required field for Sample Manifest export integration. 
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</description>
        <inlineHelpText>Set on OP creation. Applies to kit products only. Required field for Sample Manifest export integration. 
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</inlineHelpText>
        <label>Analysis Workflow</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Delivery_Mode__c</fullName>
        <formula>text(PricebookEntry.Product2.Delivery_Mode__c )</formula>
        <label>Delivery Mode</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Kit_ID__c</fullName>
        <description>Kit barcode supplied by Kit Vendor</description>
        <externalId>true</externalId>
        <inlineHelpText>Kit barcode supplied by Kit Vendor</inlineHelpText>
        <label>Kit ID (Raw)</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Prep_Request__c</fullName>
        <formula>text( PricebookEntry.Product2.Prep_Request__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prep Request</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Project_Name__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration. Project Name is generated for Kit Order Product Lines when Accession Status = PASS. The project name is the date of the Monday in the week the kit passes accessioning and the sample manifest is submitted.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration. Project Name is generated for Kit Order Product Lines when Accession Status = PASS. The project name is the date of the Monday in the week the kit passes accessioning</inlineHelpText>
        <label>Project Name</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Registered_Date__c</fullName>
        <description>Date/Time Order Line is registered to a user</description>
        <inlineHelpText>Date/Time Order Line is registered to a user</inlineHelpText>
        <label>Registered Date</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Required_Yield__c</fullName>
        <description>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Required Yield</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Sample_Source__c</fullName>
        <formula>text( PricebookEntry.Product2.Sample_Source__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Source</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Sample_Status__c</fullName>
        <description>Sample status labels as a sample moves through the sequencing process.</description>
        <inlineHelpText>Sample status labels as a sample moves through the sequencing process.</inlineHelpText>
        <label>Sample Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Submission</fullName>
                </value>
                <value>
                    <fullName>Manifest Uploaded</fullName>
                </value>
                <value>
                    <fullName>DNA Extraction Started</fullName>
                </value>
                <value>
                    <fullName>DNA Extraction Complete</fullName>
                </value>
                <value>
                    <fullName>Library Prep Complete</fullName>
                </value>
                <value>
                    <fullName>Enrichment Complete</fullName>
                </value>
                <value>
                    <fullName>Clustering Complete</fullName>
                </value>
                <value>
                    <fullName>Rehyb/Fail FC</fullName>
                </value>
                <value>
                    <fullName>Sequencing Complete</fullName>
                </value>
                <value>
                    <fullName>Sequencing Data QC Complete</fullName>
                </value>
                <value>
                    <fullName>Sequencing Data QC Fail</fullName>
                </value>
                <value>
                    <fullName>Data Delivery Complete</fullName>
                </value>
                <value>
                    <fullName>Data Delivery Fail</fullName>
                </value>
                <value>
                    <fullName>Requeue to Saliva Tube</fullName>
                </value>
                <value>
                    <fullName>Require New Sample</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Formula field that looks up to product record and describes product type on the Order Product level. (APP or KIT)</description>
        <formula>text(PricebookEntry.Product2.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula field that looks up to product record and describes product type on the Order Product level. (APP or KIT)</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>UserId__c</fullName>
        <formula>registeredBy__r.userid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>registeredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Product level field to capture who registers a specific product.</description>
        <inlineHelpText>Order Product level field to capture who registers a specific product.</inlineHelpText>
        <label>Registered By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Products (Registered By)</relationshipLabel>
        <relationshipName>Registered_Kits_c</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds></CustomObject>

objects/Product2.object
<CustomObject><fields>
        <fullName>Analysis_Workflow__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</inlineHelpText>
        <label>Analysis Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reads_to_variants_v2.0.0</fullName>
                </value>
                <value>
                    <fullName>helix_reads_to_variants_v2.1.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.1.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.2.0-WF1.0.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.2.1-WF1.0.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Delivery_Mode__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deliver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Prep_Request__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Prep Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Helix Saliva Extraction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Required_Yield__c</fullName>
        <description>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Required Yield</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4.5</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Sample_Source__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Sample Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Saliva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Picklist that sets the type of Product, useful in reporting and other logic throughout the Order lifecycle.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>KIT</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                    <default>true</default>
                    <label>APP</label>
                </value>
                <value>
                    <fullName>S&amp;H</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>SALES TAX</fullName>
                </value>
                <value>
                    <fullName>Helix Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Helix Sequence Revenue</fullName>
                </value>
                <value>
                    <fullName>Partner Revenue Share</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><recordTypeTrackHistory>true</recordTypeTrackHistory></CustomObject>

classes/Test_RegisterKitAPI.cls
@isTest 
private class Test_RegisterKitAPI {

    static testMethod void kitTestMethod() {
            
       //Creating HM_Agreement
       HM_Agreement agreement1 = new HM_Agreement();
       agreement1.key = '1' ;
       agreement1.version = '1' ;
       agreement1.agreed = true ;
       HM_Agreement agreement2 = new HM_Agreement();
       agreement2.key = '2' ;
       agreement2.version = '2' ;
       agreement2.agreed = true ;
       List<HM_Agreement> agreements = new List<HM_Agreement>();
       agreements.add(agreement1);
       agreements.add(agreement2);
       
       HM_Contact buyerHMCon = new HM_Contact();
       buyerHMCon.firstName = 'kit';
       buyerHMCon.lastName = 'account';
       buyerHMCon.email = 'fName@lName.com';
       buyerHMCon.userId = '';
       buyerHMCon.phone = '9902944899';
       buyerHMCon.biologicalSex = 'Male';
       buyerHMCon.blackNaturally = 'Yes';
       buyerHMCon.agreements = agreements;
       
       HM_Account buyerHMAcc = new HM_Account();
       buyerHMAcc.contact = buyerHMCon;
       
       HM_Kit hmkit = new HM_Kit();
       hmkit.account = buyerHMAcc ;
       hmkit.kitId = '12345';
       
       OrderItem oi = [select id from OrderItem limit 1];
       hmkit.orderProductId= oi.id;   //'H01258692';
            
       HM_OrderLine orderLine1 = new HM_OrderLine();
       orderLine1.quantity = 2;
       orderLine1.sku = '';
       orderLine1.appId = '654321';
       
       HM_OrderLine orderLine2 = new HM_OrderLine();
       orderLine2.quantity = 3;
       orderLine2.sku = '';
       orderLine2.appId = '123456';
       
       List<HM_OrderLine> lineList = new List<HM_OrderLine>();
       lineList.add(orderLine1);
       lineList.add(orderLine2);
       
       // userid blank
       RegisterKitResponse result = RegisterKitAPI.registerKit(hmKit);
       
       hmkit.Account.contact.userId = '123456';
       result = RegisterKitAPI.registerKit(hmKit);
       
       Account createdAccount = [select Name from Account where Name = 'kit account' limit 1];
       
       System.assertEquals('kit account', createdAccount.Name);
       Account acc = new Account (Name = 'Test Account 1');
       insert acc;
       //added 27-2-2017
       Contact con = new Contact(
           FirstName = 'Test',
           LastName = 'Contact',
           AccountId =  acc.Id,
           userid__c = '456789'
       );
       insert con;
       //End
       DateTime regDate = DateTime.newInstance(2016, 11, 11, 6, 6, 0);
       
       hmKit.registeredDate = regDate;
       hmkit.account.contact.userId = '456789';  
       hmkit.account.contact.firstName = 'Tested';  
       hmkit.account.contact.lastName = 'data'; 
       hmkit.account.contact.userId = '456789';
       hmkit.account.contact.phone = '88888888';
       hmkit.account.contact.biologicalSex = 'Female';
       hmkit.account.contact.blackNaturally = 'Yes';
       
       // helix userId exists and match with existing contact
       result = RegisterKitAPI.registerKit(hmKit);
       
       con = [select LastName , FirstName, Account.Name, Phone, Naturally_Black_Hair__c, Biological_Sex__c 
                           from Contact where id = :con.id];
       System.assertEquals('Tested', con.FirstName);
       System.assertEquals('data', con.LastName);
       System.assertEquals('Tested data',con.account.name);
       System.assertEquals('88888888', con.phone);
       System.assertEquals('Yes', con.Naturally_Black_Hair__c);
       System.assertEquals('Female', con.Biological_Sex__c);
       
       oi = [select Registered_Date__c, registeredBy__c from OrderItem where id = :oi.id];
       System.assertEquals(regDate, oi.Registered_Date__c);
       System.assertEquals(con.id, oi.registeredBy__c);
       
       // helix userId does not match with any existing contact
       hmkit.account.contact.userId = '45678909';  
       result = RegisterKitAPI.registerKit(hmKit);
       // new contact record is created with new helix user id
       System.assertEquals('45678909', [select UserId__c from Contact where UserId__c = '45678909' limit 1].UserId__c);
       
       // trying to register same kit again with same contact, return error message
       result = RegisterKitAPI.registerKit(hmKit);
       System.assertEquals('Register kit API to reject kit registration because the contact is already registered to a kit that doesnot have accessioning cancelled status', result.error.message);
       
    }

    @testSetup static void createProductTestData() {
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Alpha DNA Kit', Type__c = 'KIT', Prep_Request__c = 'Helix Saliva Extraction',
            Delivery_Mode__c = 'Deliver', Sample_Source__c = 'Customer Saliva');
        insert prod;
        
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, 
            Product2Id = prod.Id, UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Account acc = new Account(Name = 'Test');
        insert acc;
        Order o = new Order(AccountId = acc.id, EffectiveDate = System.today(), Status = 'Draft', Pricebook2Id = pricebookId);
        insert o;
        List<OrderItem> oiList = new List<OrderItem>();
        for(Integer i = 100; i < 700; i++) {
            OrderItem oi = new OrderItem(OrderId = o.id, Required_Yield__c = 4.5, Project_Name__c = 'TestProject_5-31',
                Analysis_Workflow__c = 'ExomePlusFastq2GvcfV1.0-WFV1.0', Sample_Status__c = 'Ready for Submission',
                PricebookEntryId = standardPrice.id, Quantity = 1, UnitPrice = 100);
            oi.Kit_ID__c = 'AAAAAAA' + String.valueOf(i);
            oiList.add(oi);
        }
        insert oiList;
        System.assertEquals(600, oiList.size());
        // Next, perform some tests with your test price book entries.
    }
}