objects/Contact.object
<CustomObject><fields>
        <fullName>Biological_Sex__c</fullName>
        <description>User registration data passed by Helix Marketplace API.</description>
        <inlineHelpText>User registration data passed by Helix Marketplace API.</inlineHelpText>
        <label>Biological Sex</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>userid__c</fullName>
        <description>User registration data passed by Helix Marketplace API.</description>
        <externalId>true</externalId>
        <inlineHelpText>User registration data passed by Helix Marketplace API.</inlineHelpText>
        <label>UserID</label>
        <length>39</length>
        <type>Text</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ControlledByParent</sharingModel></CustomObject>

objects/OrderItem.object
<CustomObject><fields>
        <fullName>Analysis_Workflow__c</fullName>
        <description>Set on OP creation. Applies to kit products only. Required field for Sample Manifest export integration. 
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</description>
        <inlineHelpText>Set on OP creation. Applies to kit products only. Required field for Sample Manifest export integration. 
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</inlineHelpText>
        <label>Analysis Workflow</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields>
        <fullName>BillTo_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Required for Email Alerts triggered at the Order Item level.</description>
        <inlineHelpText>Required for Email Alerts triggered at the Order Item level.</inlineHelpText>
        <label>BillTo Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Products (BillTo Contact)</relationshipLabel>
        <relationshipName>Order_Products_BillTo</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Delivery_Mode__c</fullName>
        <formula>text(PricebookEntry.Product2.Delivery_Mode__c )</formula>
        <label>Delivery Mode</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Kit_ID__c</fullName>
        <description>Kit barcode supplied by Kit Vendor</description>
        <externalId>true</externalId>
        <inlineHelpText>Kit barcode supplied by Kit Vendor</inlineHelpText>
        <label>Kit ID (Raw)</label>
        <length>25</length>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Last_Accessioning_Scan__c</fullName>
        <description>Date/Time of last accessioning scan into accessioning module</description>
        <inlineHelpText>Date/Time of last accessioning scan into accessioning module</inlineHelpText>
        <label>Last Accessioning Scan</label>
        <type>DateTime</type>
    </fields><fields>
        <fullName>Prep_Request__c</fullName>
        <formula>text( PricebookEntry.Product2.Prep_Request__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prep Request</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Project_Name__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration. Project Name is generated for Kit Order Product Lines when Accession Status = PASS. The project name is the date of the Monday in the week the kit passes accessioning and the sample manifest is submitted.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration. Project Name is generated for Kit Order Product Lines when Accession Status = PASS. The project name is the date of the Monday in the week the kit passes accessioning</inlineHelpText>
        <label>Project Name</label>
        <length>20</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Required_Yield__c</fullName>
        <description>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Required Yield</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields><fields>
        <fullName>Sample_Source__c</fullName>
        <formula>text( PricebookEntry.Product2.Sample_Source__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sample Source</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Sample_Status__c</fullName>
        <description>Sample status labels as a sample moves through the sequencing process.</description>
        <inlineHelpText>Sample status labels as a sample moves through the sequencing process.</inlineHelpText>
        <label>Sample Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Ready for Submission</fullName>
                </value>
                <value>
                    <fullName>Manifest Uploaded</fullName>
                </value>
                <value>
                    <fullName>DNA Extraction Started</fullName>
                </value>
                <value>
                    <fullName>DNA Extraction Complete</fullName>
                </value>
                <value>
                    <fullName>Library Prep Complete</fullName>
                </value>
                <value>
                    <fullName>Enrichment Complete</fullName>
                </value>
                <value>
                    <fullName>Clustering Complete</fullName>
                </value>
                <value>
                    <fullName>Rehyb/Fail FC</fullName>
                </value>
                <value>
                    <fullName>Sequencing Complete</fullName>
                </value>
                <value>
                    <fullName>Sequencing Data QC Complete</fullName>
                </value>
                <value>
                    <fullName>Sequencing Data QC Fail</fullName>
                </value>
                <value>
                    <fullName>Data Delivery Complete</fullName>
                </value>
                <value>
                    <fullName>Data Delivery Fail</fullName>
                </value>
                <value>
                    <fullName>Requeue to Saliva Tube</fullName>
                </value>
                <value>
                    <fullName>Require New Sample</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>ShipTo_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Required for Email Alerts triggered at the Order Item level.</description>
        <inlineHelpText>Required for Email Alerts triggered at the Order Item level.</inlineHelpText>
        <label>ShipTo Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Products (ShipTo Contact)</relationshipLabel>
        <relationshipName>Order_Products_ShipTo</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Formula field that looks up to product record and describes product type on the Order Product level. (APP or KIT)</description>
        <formula>text(PricebookEntry.Product2.Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Formula field that looks up to product record and describes product type on the Order Product level. (APP or KIT)</inlineHelpText>
        <label>Type</label>
        <type>Text</type>
    </fields><fields>
        <fullName>UserId__c</fullName>
        <formula>registeredBy__r.userid__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>registeredBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Order Product level field to capture who registers a specific product.</description>
        <inlineHelpText>Order Product level field to capture who registers a specific product.</inlineHelpText>
        <label>Registered By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Order Products (Registered By)</relationshipLabel>
        <relationshipName>Registered_Kits_c</relationshipName>
        <type>Lookup</type>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds></CustomObject>

objects/Product2.object
<CustomObject><fields>
        <fullName>Analysis_Workflow__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.
(The format used is &lt;App&gt;&lt;App Version&gt;&lt;Workflow Tag&gt;&lt;Workflow version&gt;)</inlineHelpText>
        <label>Analysis Workflow</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>reads_to_variants_v2.0.0</fullName>
                </value>
                <value>
                    <fullName>helix_reads_to_variants_v2.1.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.1.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.2.0-WF1.0.0</fullName>
                </value>
                <value>
                    <fullName>helix_r2v_v2.2.1-WF1.0.0</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Delivery_Mode__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Delivery Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deliver</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Prep_Request__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Prep Request</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Helix Saliva Extraction</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Required_Yield__c</fullName>
        <description>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Required Yield in GB. Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Required Yield</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4.5</fullName>
                </value>
                <value>
                    <fullName>6.1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Sample_Source__c</fullName>
        <description>Applies to kit products only. Required field for Sample Manifest export integration.</description>
        <inlineHelpText>Applies to kit products only. Required field for Sample Manifest export integration.</inlineHelpText>
        <label>Sample Source</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Saliva</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><fields>
        <fullName>Type__c</fullName>
        <description>Picklist that sets the type of Product, useful in reporting and other logic throughout the Order lifecycle.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>KIT</fullName>
                </value>
                <value>
                    <fullName>APP</fullName>
                    <default>true</default>
                    <label>APP</label>
                </value>
                <value>
                    <fullName>S&amp;H</fullName>
                </value>
                <value>
                    <fullName>OTHER</fullName>
                </value>
                <value>
                    <fullName>SALES TAX</fullName>
                </value>
                <value>
                    <fullName>Helix Referral Fee</fullName>
                </value>
                <value>
                    <fullName>Helix Sequence Revenue</fullName>
                </value>
                <value>
                    <fullName>Partner Revenue Share</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>false</enableFeeds><recordTypeTrackHistory>true</recordTypeTrackHistory></CustomObject>

objects/Sample_Service_Credentials__c.object
<CustomObject><fields>
        <fullName>Login_Service__c</fullName>
        <label>Login Service</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields><fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><label>Sample Service Credentials</label><nameField>
        <label>Sample Service Credentials Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Sample Service Credentials</pluralLabel><sharingModel>ReadWrite</sharingModel><visibility>Public</visibility></CustomObject>

classes/Test_ManifestDataUtil.cls
@isTest
public class Test_ManifestDataUtil {
    
    public static void createProductTestData() {
        
        // First, set up test price book entries.
        // Insert a test product.
        Product2 prod = new Product2(Name = 'Alpha DNA Kit', Type__c = 'KIT', Prep_Request__c = 'Helix Saliva Extraction',
            Delivery_Mode__c = 'Deliver', Sample_Source__c = 'Customer Saliva');
        insert prod;
        
        // Get standard price book ID.
        // This is available irrespective of the state of SeeAllData.
        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod.Id,
                                                UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Account acc = new Account(Name = 'Test');
        insert acc;
        Contact con = new Contact(LastName = 'Test', AccountId = acc.Id, UserId__c = '1111', 
                            BirthDate = System.today().addYears(-12), Biological_Sex__c = 'Female');
        insert con;
        Order o = new Order(AccountId = acc.id, EffectiveDate = System.today(), Status = 'Draft', Pricebook2Id = pricebookId,
                        BillToContactId = con.id, ShipToContactId = con.id);
        insert o;
        List<OrderItem> oiList = new List<OrderItem>();
        for(Integer i = 100; i < 700; i++) {
            OrderItem oi = new OrderItem(OrderId = o.id, Required_Yield__c = 4.5, Project_Name__c = 'TestProject_5-31',
                Analysis_Workflow__c = 'ExomePlusFastq2GvcfV1.0-WFV1.0', Sample_Status__c = 'Ready for Submission',
                PricebookEntryId = standardPrice.id, Quantity = 1, UnitPrice = 100, BillTo_Contact__c = con.id, ShipTo_Contact__c = con.id,
                registeredBy__c = con.id, Last_Accessioning_Scan__c = System.now().addMinutes(i));
            oi.Kit_ID__c = 'AAAAAAA' + String.valueOf(i);
            oiList.add(oi);
        }
        insert oiList;
        System.assertEquals(600, oiList.size());
        // Next, perform some tests with your test price book entries.
    }
    
    public static void createFakeResponse() {
        SampleStatusResponse response = new SampleStatusResponse();
        List<SampleStatus> ssList = new List<SampleStatus>();
        for(Integer i = 100; i < 700; i++) {
            SampleStatus s = new SampleStatus();
            s.kitId = 'AAAAAAA' + String.valueOf(i);
            s.sampleStatus = 'Manifest Uploaded';
            s.statusTimestamp = DateTime.newInstance(2016, 9, 9, 1, 1, 1);
            ssList.add(s);
        }
        response.sampleStatuses = ssList;
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'OK',
                                                 JSON.serializePretty(response),
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
    }
    
    
    public static void createResponse() {
        SampleStatusResponse response = new SampleStatusResponse();
        List<SampleStatus> ssList = new List<SampleStatus>();
        for(Integer i = 100; i < 700; i++) {
            SampleStatus s = new SampleStatus();
            s.kitId = 'AAAAAAA' + String.valueOf(i);
            s.sampleStatus = 'Data Delivery Complete';
            s.statusTimestamp = DateTime.newInstance(2016, 10, 9, 1, 1, 1);
            ssList.add(s);
        }
        response.sampleStatuses = ssList;
        
        SingleRequestMock fakeResponse = new SingleRequestMock(200,
                                                 'OK',
                                                 JSON.serializePretty(response),
                                                 null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
    }
    
    // create upload manifest settings data
    public static Sample_Service_Credentials__c uploadManifestSettings() {
        Sample_Service_Credentials__c ssc = new Sample_Service_Credentials__c();
        ssc.Name = 'UploadManifest';
        ssc.Username__c = 'TestUsername';
        ssc.Password__c = 'TestPassword';
        ssc.Login_Service__c = 'www.testlogin.com';
        ssc.Sample_Status_Service__c = 'www.ssc.com';
        ssc.Frequency__c = 5;
        ssc.StartTime__c = '9:00';
        ssc.EndTime__c = '21:00';
        ssc.Record_Count__c = 1000;
        ssc.Query_Limit__c = 1000;
        ssc.Scope__c = 'samplestatus_sfdc';
        insert ssc;
        return ssc;
    }
    
    public static void uploadStatusDateMapping() {
        SampleStatusDateMapping__c statusDateMap = new SampleStatusDateMapping__c(
                Name = 'Data Delivery Complete',
                Date_Field_API_Name__c = 'Data_Delivery_Date__c'
        );
        insert statusDateMap;
    }
}